databases:
  - name: connected-db
    databaseName: ConnectED
    user: connected_user
    plan: free

services:
  - type: web
    name: connected-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: connected-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: connected-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: connected-db
          property: password
      - key: JWT_SECRET
        value: 4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjW
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: 8080
